package org.ekstep.analytics.framework

object GraphQueryParams {
	val UNIQUE_KEY = "IL_UNIQUE_ID"
	
	val CREATE = "CREATE";
	val MERGE = "MERGE"
	val MATCH = "MATCH";
	val RETURN = "RETURN";
	val DETACH_DELETE = "DETACH DELETE"
	
	val OPEN_CURLY_BRACKETS = "{";
	val CLOSE_CURLY_BRACKETS = "}";
	val OPEN_COMMON_BRACKETS_WITH_NODE_OBJECT_VARIABLE = "(ee:";
	val OPEN_COMMON_BRACKETS_WITH_NODE_OBJECT_VARIABLE_WITHOUT_COLON = "(ee";
	val OPEN_COMMON_BRACKETS = "(";
	val CLOSE_COMMON_BRACKETS = ")";
	val COLON = ": ";
	val SINGLE_QUOTE = "'";
	val COMMA = ", ";
	val BLANK_SPACE = " ";
	val EQUALS = "=";
	val DEFAULT_CYPHER_NODE_OBJECT = "ee";
	val DEFAULT_CYPHER_NODE_OBJECT_II = "aa";
	val DOT = ".";
	val DASH = "-";
	val DEFAULT_CYPHER_RELATION_OBJECT = "r";
	val DEFAULT_CYPHER_START_NODE_OBJECT = "__startNode";
	val DEFAULT_CYPHER_END_NODE_OBJECT = "__endNode";
	val DEFAULT_CYPHER_COUNT_OBJECT = "__count";
	val OPEN_SQUARE_BRACKETS = "[";
	val CLOSE_SQUARE_BRACKETS = "]";
	val METADATA_KEY_PREFIX = " { MD_KEY_";
	val METADATA_VALUE_PREFIX = " { MD_VALUE_";
	val SYSTEM_PROPERTIES_KEY_PREFIX = " { SP_KEY_";
	val SYSTEM_PROPERTIES_VALUE_PREFIX = " { SP_VALUE_";
	val AUDIT_PROPERTIES_KEY_PREFIX = " { AP_KEY_";
	val AUDIT_PROPERTIES_VALUE_PREFIX = " { AP_VALUE_";
	val VERSION_PROPERTIES_KEY_PREFIX = " { VP_KEY_";
	val VERSION_PROPERTIES_VALUE_PREFIX = " { VP_VALUE_";
}

object RelationshipDirection extends Enumeration {
	type Direction = Value;
	val OUTGOING, INCOMING, BIDIRECTIONAL = Value
	
}